# Generated by Django 3.2.20 on 2023-09-04 07:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migmig', '0003_alter_flightdetails_traveler_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='traveler_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
