# Generated by Django 3.2.20 on 2023-09-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migmig', '0006_auto_20230909_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
